django 초기세팅 완료
wecode-bootcamp-korea/bang_olaf-backend pull request #2
Opened 2021-01-11 11:09 UTC by xchdtk

2021-01-11 12:13 UTC, soheon-lee commented on bangoraf/settings.py
> +		#만약 허용해야할 추가적인 헤더키가 있다면?(사용자정의 키) 여기에 추가하면 됩니다.
이 주석은 안내사항이기 때문에 제거해주시는 것이 좋습니다

2021-01-11 12:13 UTC, soheon-lee commented on my_settings.py
> +SECRET = '시크릿키'
my_settings.py는 git에 올라오는 파일이 아닙니다 :) 실제 데이터베이스 정보가 입력되어있다면 중요한 정보가 노출되기 때문입니다

2021-01-11 12:13 UTC, soheon-lee commented on bangoraf/settings.py
> +SECRET_KEY = 'bx+)bh7mi(1otq5-y-)v%e*ot2n&nqu^boc_%2epkhk)1ei-#5'
진수님이 my_settings.py에 입력해두신 secret_key로 대체해주세요

2021-01-12 01:23 UTC, lordmyshepherd requested changes

2021-01-12 01:23 UTC, lordmyshepherd commented on requirements.txt
> +Flask==1.1.2
이 프로젝트에서 Flask가 필요한가요?
requirements.txt ( dependancy)는 프로젝트에 필요한 페키지만 기록해주세요.
사용하지 않는 페키지 때문에 프로젝트가 무거워지면 안되겠죠?

2021-01-12 01:58 UTC, lordmyshepherd requested changes

2021-01-12 01:58 UTC, lordmyshepherd commented on requirements.txt
> +zipp==1.2.0
`mysqlclient` 라이브러리는 안보이네요.
`python manage.py runserver` 명령어로 server가 정상적으로 실행되는지 확인해보셨나요?

2021-01-12 01:59 UTC, lordmyshepherd requested changes

2021-01-12 01:59 UTC, lordmyshepherd commented on requirements.txt
> +zipp==1.2.0
`zipp` 어떤는 어떤 라이브러리인가요?
Flask 페키지 설치하면서 함께 설치된 라이브러리들이 보이네요.
가상환경을 새로 만들어주시고 이번 프로젝트에 필요한 페키지만 설치해주세요~

2021-01-12 02:47 UTC, lordmyshepherd approved these changes

2021-01-12 02:47 UTC, lordmyshepherd commented
LGTM 👍

2021-01-12 02:47 UTC, merged